Prettied up the build script and added checking for quilt in the kernel srcctrl script

diff --git a/srcctrl/kernel b/srcctrl/kernel
--- a/srcctrl/kernel
+++ b/srcctrl/kernel
@@ -28,6 +28,14 @@ unpack () {
 }
 
 build () {
+
+  which quilt > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
+     echo "Can't find the 'quilt' command - can't patch kernel w/ EDAC support."
+     return 1
+  fi
+
   if [ ! -f ${SRCDIR}/${DIRNAME}/.config ]
   then
     if [ ! -e ${PATCHDIR}/kernel.${ARCH}.config ]
@@ -40,13 +48,8 @@ build () {
     cd ${SRCDIR}/${DIRNAME}
 
     quilt push -af
-    #if [ $? != 0 ]
-    #then
-    #  echo "Patching in EDAC failed."
-    #  return 1
-    #fi
-
     make clean
+
     make oldconfig
     if [ $? != 0 ]
     then
