make a symlink to udevtrigger for udevadm

diff --git a/srcctrl/udev b/srcctrl/udev
--- a/srcctrl/udev
+++ b/srcctrl/udev
@@ -35,6 +35,27 @@ build () {
   markdone
 }
 
+install () {
+  cd ${SRCDIR}/${DIRNAME}
+  for file in ${BINARIES}; do
+    cp -vp ${file} ${STAGEDIR}/usr/bin
+    if [ $? != 0 ]; then
+      echo "Copying a required binary ${file} failed. Please check $0"
+      return 1
+    fi
+  done
+
+  for file in ${SBINARIES}; do
+    cp -vp ${file} ${STAGEDIR}/usr/sbin
+    if [ $? != 0 ]; then
+      echo "Copying a required sbin binary ${file} failed. Please check $0"
+      return 1
+    fi
+  done
+  
+  ln -s udevadm ${STAGEDIR}/usr/bin/udevtrigger
+}
+
 $1 $2
 
 if [ $? != 0 ]; then
